author = "Oxalin"
country_code = "GB"
description = "Section 2 of High Speed 1, from Southfleet Junction to London St Pancras International"
display_name = "High Speed 1"
doc_files = [ "High Speed 1.md",]
factual = true
img_files = [ "High Speed 1.bmp",]
name = "High Speed 1"
release_date = "2023-01-18"
rly_file = "High Speed 1.rly"
ssn_files = [ "High Speed 1 Initial Session.ssn",]
ttb_files = [ "High Speed 1 25-01-23.ttb",]
version = "1.0.0"
year = 2023
signal_position = "left"
contributors = []
